Repository atlp-rwanda/script-heroes-bn-backend, pull requests merged in 2020-09, with the labels that each got.

#3 #174797505 eslint for linting
  .eslintrc.json
  package-lock.json
  package.json
  src/.prettierrc.json
  src/index.js
Labels: TTL review

#2 #174797506 integrate houndci with readme badge
  .hound.yml
  README.md
Labels: ready for review

#6 #174797503 Configure BareFoot Nomad to use PostgreSQL
  .gitignore
  package.json
  src/.babelrc
  src/config/index.js
  src/config/passport.js
  src/controllers/index.js
  src/database/config.js
  src/index.js
  src/middlewares/index.js
  src/models/User.js
  src/routes/api/index.js
  src/routes/api/users.js
  src/routes/index.js
  src/services/index.js
  src/utils/index.js
  src/validation/index.js
Labels: ready for review

#8 #174797511-Swagger Documentation
  .gitignore
  README.md
  package-lock.json
  package.json
  src/Swagger.json
  src/index.js
Labels: ready for review

#5 #174797507 Integrate TravisCI with readme badge
  .travis.yml
  README.md
  src/index.js
  src/swagger.json
Labels: TTL review, ready for review

#10 #174797510 Integrate coveralls code coverage service
  .coveralls.yml
  .gitignore
  README.md
  package-lock.json
  package.json
  src/index.js
Labels: TTL review, ready for review

#12 #174797514 Deploy base application to Heroku
  Procfile
  README.md
  package.json
  src/.babelrc
  src/index.js
  swagger.json
Labels: ready for review

#9 #174797504 setup sequelize
  .sequelizerc
  .travis.yml
  README.md
  package-lock.json
  package.json
  src/.babelrc
  src/database/config.js
  src/database/migrations/20200923104050-create-user.js
  src/database/models/index.js
  src/database/models/user.js
  src/database/seeders/20200923110300-demo-user.js
  src/index.js
  src/routes/api/index.js
  src/routes/index.js
  test/index.test.js
Labels: ready for review

#4 #174797509 Dotenv setup
  .babelrc
  .env-example
  .travis.yml
  README.md
  package.json
  src/.babelrc
  src/database/config.js
  src/database/models/index.js
  src/database/models/user.js
  src/index.js
  src/swagger.json
Labels: ready for review

#14 #174797515 Add JSON web token
  .env-example
  package.json
  src/utils/jwtFunctions.js
  test/jwtFunctions.test.js
Labels: TTL review, ready for review

#11 #174848252 Create User Signup Endpoint
  README.md
  package-lock.json
  package.json
  src/controllers/signup.js
  src/database/config.js
  src/database/migrations/20200927093745-create-user.js
  src/database/models/user.js
  src/database/seeders/20200923110300-demo-user.js
  src/database/seeders/20200927094532-user.js
  src/index.js
  src/middlewares/asynchandler.js
  src/routes/api/index.js
  src/routes/signup.js
  src/validations/signup.js
  swagger.json
  test/controllers/signup.test.js
Labels: TTL review

#13 #174797453 Implement multiple languages support
  .eslintrc.json
  .hound.yml
  package-lock.json
  package.json
  src/controllers/signup.js
  src/index.js
  src/utils/internationalization/i18n.js
  src/utils/internationalization/locales/en.json
  src/utils/internationalization/locales/fr.json
  src/utils/internationalization/locales/kin.json
Labels: TTL review, ready for review

#22 #174797514 Fix Heroku Deployment
  package-lock.json
  package.json
Labels: TTL review, ready for review

#15 #174797518 Login using email and password
  README.md
  package.json
  src/controllers/emailAuth.js
  src/controllers/signup.js
  src/database/models/index.js
  src/index.js
  src/middlewares/validations/userValidation.js
  src/routes/auth/emailAuth.js
  src/routes/index.js
  src/routes/signup.js
  src/utils/internationalization/locales/en.json
  src/utils/internationalization/locales/fr.json
  src/utils/internationalization/locales/kin.json
  src/validations/signup.js
  swagger.json
  test/controllers/login.test.js
  test/controllers/signup.test.js
Labels: TTL review, ready for review
